# Generated by Django 5.1.6 on 2025-04-04 20:41

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('logo', models.CharField(default='', max_length=200)),
                ('website', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('proof_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('requirement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=200)),
                ('examples', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('term_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('reward_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('code', models.CharField(default='', max_length=300)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyTaskService.company')),
                ('terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyTaskService.terms')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscription_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starts_on', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('end_on', models.DateTimeField()),
                ('frequency', models.CharField(choices=[('NONE', 0), ('DAILY', 1), ('WEEKLY', 7), ('MONTHLY', 30)], default='NONE', max_length=20)),
                ('streak', models.IntegerField(default=0)),
                ('max_streak', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('UPCOMING', 'UPCOMING'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('OVERDUE', 'OVERDUE')], default='UPCOMING', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('snapshot_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_on', models.DateTimeField()),
                ('ended_on', models.DateTimeField()),
                ('snapshot_status', models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='FAILED', max_length=20)),
                ('proof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyTaskService.proof')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyTaskService.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=200)),
                ('frequency', models.CharField(choices=[('NONE', 0), ('DAILY', 1), ('WEEKLY', 7), ('MONTHLY', 30)], default='NONE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('starts_on', models.DateTimeField()),
                ('ends_on', models.DateTimeField()),
                ('task_type', models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('PRIVATE', 'PRIVATE')], default='PRIVATE', max_length=10)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyTaskService.requirement')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyTaskService.reward')),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyTaskService.task'),
        ),
    ]
