# Generated by Django 5.1.6 on 2025-04-05 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyTaskService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EasyTaskService.requirement'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EasyTaskService.reward'),
        ),
    ]
