# Generated by Django 5.1.6 on 2025-04-05 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EasyTaskService', '0003_alter_task_description_alter_task_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='end_on',
            new_name='ends_on',
        ),
    ]
