# Generated by Django 5.1.6 on 2025-04-05 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EasyTaskService', '0004_rename_end_on_subscription_ends_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snapshot',
            old_name='ended_on',
            new_name='completed_on',
        ),
    ]
