# Generated by Django 5.1.6 on 2025-04-06 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyTaskService', '0005_rename_ended_on_snapshot_completed_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='frequency',
            field=models.CharField(choices=[('NONE', datetime.timedelta(0)), ('MINUTE', datetime.timedelta(seconds=60)), ('HOURLY', datetime.timedelta(seconds=3600)), ('DAILY', datetime.timedelta(days=1)), ('WEEKLY', datetime.timedelta(days=7))], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='frequency',
            field=models.CharField(choices=[('NONE', datetime.timedelta(0)), ('MINUTE', datetime.timedelta(seconds=60)), ('HOURLY', datetime.timedelta(seconds=3600)), ('DAILY', datetime.timedelta(days=1)), ('WEEKLY', datetime.timedelta(days=7))], default='NONE', max_length=20),
        ),
    ]
