# Generated by Django 5.1.6 on 2025-04-18 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyTaskService', '0006_alter_subscription_frequency_alter_task_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='proof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EasyTaskService.proof'),
        ),
    ]
