# Generated by Django 5.1.6 on 2025-04-19 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyTaskService', '0007_alter_snapshot_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='snapshot_status',
            field=models.CharField(default='FAILED', max_length=20),
        ),
    ]
