# Generated by Django 5.1.6 on 2025-05-17 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EasyTaskService', '0008_alter_snapshot_snapshot_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proof',
            old_name='image',
            new_name='image_uri',
        ),
    ]
