# Generated by Django 5.1.6 on 2025-07-02 00:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyTaskService', '0009_rename_image_proof_image_uri'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('milestone_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_on', models.DateTimeField()),
                ('completed_on', models.DateTimeField()),
                ('ends_on', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('subscription_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyTaskService.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
