# Generated by Django 5.1.6 on 2025-07-02 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyTaskService', '0010_milestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='completed_on',
            field=models.DateTimeField(null=True),
        ),
    ]
