# Generated by Django 5.1.6 on 2025-07-02 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyTaskService', '0011_alter_milestone_completed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='proof',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='EasyTaskService.milestone'),
        ),
    ]
