# Generated by Django 5.1.6 on 2025-07-02 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EasyTaskService', '0012_proof_milestone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milestone',
            old_name='subscription_id',
            new_name='subscription',
        ),
    ]
